#!/bin/bash

# https://docs.docker.com/docker-cloud/builds/advanced/

function add_tag() {
  docker tag $IMAGE_NAME $DOCKER_REPO:$1
  docker push $DOCKER_REPO:$1
}

add_tag latest
add_tag swift-5
add_tag swift-5.3
add_tag swift-5.3.2
add_tag ${SOURCE_BRANCH}
add_tag ${SOURCE_BRANCH}_swift-5
add_tag ${SOURCE_BRANCH}_swift-5.3
add_tag ${SOURCE_BRANCH}_swift-5.3.2

exit $?
