#!/bin/bash

# https://docs.docker.com/docker-cloud/builds/advanced/

function add_tag() {
  docker tag $IMAGE_NAME $DOCKER_REPO:$1
  docker push $DOCKER_REPO:$1
}

add_tag swift-4.2.3
add_tag ${SOURCE_BRANCH}_swift-4.2.3

exit $?
